import { type Application, type ControllerConstructor } from "@hotwired/stimulus";
import {
	AccordionController,
	AvatarController,
	CalendarController,
	CarouselController,
	CharacterCountController,
	CheckboxGroupController,
	ClipboardController,
	ComboboxController,
	ColorPickerController,
	DateFieldController,
	DialogController,
	DisclosureController,
	DropdownMenuController,
	FileDropController,
	GridController,
	HoverCardController,
	ImageCropperController,
	LandmarkNavigationController,
	ListboxController,
	ListReorderController,
	NumberFieldController,
	PasswordFieldController,
	SliderController,
	SplitterController,
	TableSelectController,
	TableSortController,
	TableOfContentsController,
	TimerController,
	EditableController,
	TabsController,
	TagInputController,
	TimeFieldController,
	ToastController,
	ToggleGroupController,
	ToolbarController,
	TooltipController,
	TreeController,
	TreegridController,
} from "../src/index";

export const registrations: readonly (readonly [string, ControllerConstructor])[] = [
	["accordion", AccordionController],
	["avatar", AvatarController],
	["calendar", CalendarController],
	["carousel", CarouselController],
	["character-count", CharacterCountController],
	["checkbox-group", CheckboxGroupController],
	["clipboard", ClipboardController],
	["combobox", ComboboxController],
	["color-picker", ColorPickerController],
	["date-field", DateFieldController],
	["dialog", DialogController],
	["disclosure", DisclosureController],
	["dropdown-menu", DropdownMenuController],
	["file-drop", FileDropController],
	["grid", GridController],
	["hover-card", HoverCardController],
	["image-cropper", ImageCropperController],
	["landmark-navigation", LandmarkNavigationController],
	["listbox", ListboxController],
	["list-reorder", ListReorderController],
	["number-field", NumberFieldController],
	["password-field", PasswordFieldController],
	["slider", SliderController],
	["splitter", SplitterController],
	["table-select", TableSelectController],
	["table-sort", TableSortController],
	["table-of-contents", TableOfContentsController],
	["tabs", TabsController],
	["tag-input", TagInputController],
	["time-field", TimeFieldController],
	["timer", TimerController],
	["editable", EditableController],
	["toast", ToastController],
	["toggle-group", ToggleGroupController],
	["toolbar", ToolbarController],
	["tooltip", TooltipController],
	["tree", TreeController],
	["treegrid", TreegridController],
];

export const registerAll = (application: Application) => {
	for (const [identifier, controller] of registrations) {
		application.register(identifier, controller);
	}
};
